# fly.toml app configuration file generated for btred on 2023-11-15T10:33:25+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "btred"
primary_region = "den"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
